import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('pt');
  
  const t = (lang, key) => {

    
    const translations = {
      pt: {
        // Cabeçalho e informações gerais
        StuffedCrust: "Borda",
        orderSentSuccess:'Pedido enviado com sucesso',
        restaurantName: 'Pizzaria Italiana',
        since: 'Desde 1995',
        title: 'Autêntica Pizza Italiana',
        subtitle: 'Feita com ingredientes importados diretamente da Itália',
        yourCart: 'Seu Carrinho',
        cart: 'Carrinho',
        stampsEarned:'Selos Ganhos',
        emptyCart: 'Seu carrinho está vazio',
        emptyCartMessage: 'Adicione itens deliciosos para começar seu pedido',
        exploreMenu: 'Explorar Menu',
        viewCart: 'Ver Carrinho',
        fullMenu: 'Cardápio Completo',
        ourMenu: 'Nosso Cardápio',
        add: 'Adicionar',
        addToCart: 'Adicionar ao Carrinho',
        items: 'itens',
        subtotal: 'Subtotal',
        deliveryFee: 'Taxa de Entrega',
        discount: 'Desconto',
        total: 'Total',
        estimatedTotal: 'Total Estimado',
        free: 'Grátis',
        proceedToCheckout: 'Finalizar Pedido',
        newOrder: 'Novo Pedido',
        orderNumber: 'Número do Pedido',
        orderConfirmed: 'Pedido Confirmado!',
        confirmationMessage: 'Seu pedido foi confirmado!',
        confirmationMessageStamps: 'Seu pedido foi pago com selos!',
        confirmationMessagePickup: 'Seu pedido está sendo preparado! Retire em aproximadamente 30 minutos.',
        confirmationMessageDelivery: 'Seu pedido está a caminho! Entregaremos em aproximadamente 30-45 minutos.',
        contactMessage: 'Dúvidas? Fale conosco:',
        paymentMethodLabel: 'Método de Pagamento',
        estimatedTime: 'Tempo Estimado',
        stamps: 'Selos',
        stampsAvailable: 'Selos disponíveis',
        stampsEarned: 'Selos ganhos',
        stampsInfo: 'Ganhe 1 selo a cada 15€ gastos. 5 selos = Pão de Alho grátis!',
        stampsToUse: 'Selos utilizados',
        notEnoughStamps: 'Selos insuficientes',
        changeFor: 'Troco para',
        changeExample: 'ex: 20.00',
        notes: 'Observações',
        notesPlaceholder: 'Alguma observação sobre seu pedido?',
        deliveryInfo: 'Informações de Entrega',
        paymentMethod: 'Método de Pagamento',
        address: 'Endereço',
        addressPlaceholder: 'Rua, número e complemento',
        neighborhood: 'Bairro',
        selectNeighborhood: 'Selecione seu bairro',
        fullName: 'Nome Completo',
        phone: 'Telefone',
        pickup: 'Retirada',
        pickupAddress: 'Av. São Paulo, 123 - Portimão',
        delivery: 'Entrega',
        deliveryArea: 'Entregamos na sua região',
        viewDeliveryZones: 'Ver zonas de entrega',
        deliveryFee: 'Taxa de Entrega',
        backToCart: 'Voltar ao Carrinho',
        cash: 'Dinheiro',
        card: 'Cartão',
        mbway: 'MBWay',
        mbwayNumber: 'Número MBWay',
        mbwayDescription: 'Pagamento via MBWay',
        cashDescription: 'Pagamento na entrega',
        cardDescription: 'Pagamento com cartão',
        orderSummary: 'Resumo do Pedido',
        stampsDescription: '5€ de desconto por cada 5 selos',
        size: 'Tamanho',
        border: 'Borda',
        StuffedCrust: 'Selecione a Borda',
        noBorder: 'Sem Borda',
        addExtras: 'Adicionais',
        extras: 'Extras',
        extrasTotal: 'Total de adicionais',
        quantity: 'Quantidade',
        redeemStamps: 'Resgatar Selos',
        stampsRedeemedSuccess: 'Selos resgatados com sucesso!',
        productAddedToCart: 'Produto adicionado ao carrinho',
        garlicBread: 'Pão de Alho',
        individualPizza: 'Pizza Individual',
        mediumPizza: 'Pizza Média',
        familyPizza: 'Pizza Família',
        selectedCoupon: 'Cupom selecionado',
        confirmStampsPayment: 'Confirmar Pagamento com Selos',
        completeOrder: 'Completar Pedido',
        orderSuccess: 'Pedido realizado com sucesso!',
        orderError: 'Erro ao processar pedido',
        orderSavedLocally: 'Pedido salvo localmente (sem conexão)',
        addedToCart: 'foi adicionado ao carrinho',
        congratulations: 'Parabéns',
        couponRedeemed: 'Cupom resgatado!',
        couponRedeemedMessage: 'Você resgatou um cupom com seus selos de fidelidade',
        couponUsageInstructions: 'Apresente este código ao fazer seu próximo pedido',
        continue: 'Continuar',
        paidWithStamps: 'Pago com selos',
        invalidRedeemProduct: 'Produto para resgate inválido',
        invalidStampsAmount: 'Quantidade de selos inválida',
        stampsRedeemError: 'Erro ao resgatar selos',
        continueToPayment:'Ir Para Pagamento >>',
        confirmOrder:'Comfirmar Pedido',
        back:'Voltar',
        useStampsForItem:"Pagar Com Selos",
        stampsUsed : "Selos Utilizados",
        useStampsForItems :"Selecionar itens para pagar com selos",
        qty : "Quantidade",
        Size : "Escolher Tamanho",
        openingHours: "Horario de Funcionamento",
        quantity: "Quantidade",

        
        // Categorias do menu
        entradas: 'Entradas',
        petiscos: 'Petiscos',
        tradicionais: 'Tradicionais',
        vegetarianas: 'Vegetarianas',
        doces: 'Doces',
        bordas: 'Bordas',
        massas: 'Massas',
        todos: 'Todos',
        sobremesas: 'Sobremesas',
        bebidas: 'Bebidas',
        vinhos: 'Vinhos',
        
        // Tamanhos
        individual: 'Individual',
        media: 'Média',
        familia: 'Família',
        
        // Popular tag
        popular: 'Popular',
        new: 'Novo',

        // Fidelidade
        backToMenu: 'Voltar ao Menu',
        yourLoyaltyCard: 'Seu Cartão de Fidelidade',
        howItWorks: 'Como Funciona',
        earnStamps: 'Ganhe Selos',
        earnStampsDescription: 'A cada compra realizada, você ganha selos que são automaticamente adicionados ao seu cartão de fidelidade.',
        redeemRewards: 'Utilize Seus Selos',
        redeemRewardsDescription: 'Ao fazer um pedido, você pode utilizar seus selos acumulados para obter benefícios diretamente no carrinho.',
        enjoy: 'Benefícios',
        enjoyDescription: 'Quanto mais selos você acumula, maiores são os benefícios que você pode aproveitar em seus pedidos.',
        loginRequiredTitle: 'Login necessário',
        loginRequiredMessage: 'Faça login para acessar seu cartão de fidelidade e acompanhar seus selos',
        login: 'Entrar',
        logout: 'Sair',
        stampsEarnedToday: 'Selos ganhos hoje',
        totalStamps: 'Total de selos',
        loginSuccess: 'Login realizado com sucesso',
        loginError: 'Erro ao fazer login',
        logoutSuccess: 'Logout realizado com sucesso',
        logoutError: 'Erro ao fazer logout',
        errorLoadingData: 'Erro ao carregar dados'
      },
      en: {
        // Header and general info
        restaurantName: 'Italian Pizzeria',
        since: 'Since 1995',
        title: 'Authentic Italian Pizza',
        subtitle: 'Made with ingredients imported directly from Italy',
        yourCart: 'Your Cart',
        cart: 'Cart',
        emptyCart: 'Your cart is empty',
        emptyCartMessage: 'Add delicious items to start your order',
        exploreMenu: 'Explore Menu',
        viewCart: 'View Cart',
        fullMenu: 'Full Menu',
        ourMenu: 'Our Menu',
        addToCart: 'Add to Cart',
        items: 'items',
        subtotal: 'Subtotal',
        deliveryFee: 'Delivery Fee',
        discount: 'Discount',
        total: 'Total',
        estimatedTotal: 'Estimated Total',
        free: 'Free',
        proceedToCheckout: 'Checkout',
        newOrder: 'New Order',
        orderNumber: 'Order Number',
        orderConfirmed: 'Order Confirmed!',
        confirmationMessagePickup: 'Your order is being prepared! Pick it up in about 30 minutes.',
        confirmationMessageDelivery: 'Your order is on its way! Delivery in about 30-45 minutes.',
        whatsappMessage: 'Questions? Chat with us on WhatsApp',
        paymentMethodLabel: 'Payment Method',
        estimatedTime: 'Estimated Time',
        stamps: 'Stamps',
        changeFor: 'Change for',
        changeExample: 'ex: 20.00',
        notes: 'Notes',
        notesPlaceholder: 'Any special instructions?',
        deliveryInfo: 'Delivery Information',
        paymentMethod: 'Payment Method',
        address: 'Address',
        addressPlaceholder: 'Street, number and complement',
        neighborhood: 'Neighborhood',
        selectNeighborhood: 'Select your neighborhood',
        fullName: 'Full Name',
        phone: 'Phone',
        pickup: 'Pickup',
        pickupAddress: 'Av. São Paulo, 123 - Portimão',
        delivery: 'Delivery',
        deliveryArea: 'We deliver to your area',
        viewDeliveryZones: 'View delivery zones',
        deliveryFee: 'Delivery Fee',
        backToCart: 'Back to Cart',
        cash: 'Cash',
        card: 'Card',
        mbway: 'MBWay',
        mbwayNumber: 'MBWay Number',
        mbwayDescription: 'Payment via MBWay',
        cashDescription: 'Payment on delivery',
        cardDescription: 'Card payment',
        orderSummary: 'Order Summary',
        stampsDescription: '5€ discount for every 5 stamps',
        size: 'Size',
        border: 'Border',
        selectBorder: 'Select Border',
        noBorder: 'No Border',
        redeemStamps: 'Redeem Stamps',
        stampsRedeemedSuccess: 'Stamps redeemed successfully!',
        productAddedToCart: 'Product added to cart',
        garlicBread: 'Garlic Bread',
        individualPizza: 'Individual Pizza',
        mediumPizza: 'Medium Pizza',
        familyPizza: 'Family Pizza',
        invalidRedeemProduct: 'Invalid redeem product',
        invalidStampsAmount: 'Invalid stamps amount',
        stampsRedeemError: 'Error redeeming stamps',
    
        
        // Menu categories
        entradas: 'Starters',
        petiscos: 'Snacks',
        tradicionais: 'Traditional',
        vegetarianas: 'Vegetarian',
        doces: 'Desserts',
        bordas: 'Borders',
        massas: 'Pasta',
        todos: 'All',
        sobremesas: 'Desserts',
        bebidas: 'Drinks',
        vinhos: 'Wines',
        
        // Sizes
        individual: 'Individual',
        media: 'Medium',
        familia: 'Family',
        
        // Popular tag
        popular: 'Popular',
        new: 'New',

        // Menu items translations
        // Entradas
        'azeitonas': 'Olives',
        'pao-alho-simples': 'Simple Garlic Bread',
        'pao-alho-queijo': 'Garlic Bread with Cheese',
        'pao-alho-queijo-bacon': 'Garlic Bread with Cheese and Bacon',
        
        // Petiscos
        'filezinho-acebolado': 'Small Steak with Onions',
        'batatas-fritas': 'French Fries',
        'batata-gourmet': 'Gourmet Potatoes with Cheddar and Bacon',
        'calabresa-acebolada': 'Calabresa Sausage with Onions',
        'moelas': 'Gizzards in Sauce with Bread Slices (Friday)',
        
        // Tradicionais
        'marguerita': 'Margherita',
        'calabria': 'Calabria',
        'turim': 'Turin',
        'milao': 'Milan',
        'atum': 'Tuna',
        'hawai': 'Hawaiian',
        'bolonhesa': 'Bolognese',
        'alentejana': 'Alentejo Style',
        'americana': 'American',
        'sorrento': 'Sorrento',
        'pepperoni': 'Pepperoni',
        'frango-catupiry': 'Chicken with Catupiry',
        'calabresa-catupiry': 'Calabresa with Catupiry',
        'brocolos-bacon-catupiry': 'Broccoli with Bacon and Catupiry',
        'capricciosa': 'Capricciosa',
        'brasileira': 'Brazilian',
        'nostra': 'Nostra',
        'quatro-queijos': 'Four Cheeses',
        'do-chefe': "Chef's Special",
        'carioca': 'Carioca',
        'carbonara': 'Carbonara',
        'camarao-catupiry': 'Shrimp with Catupiry',
        'mediterranica': 'Mediterranean',
        'lombo-acebolado': 'Smoked Pork Loin with Onions',
        'lombo-catupiry': 'Smoked Pork Loin with Catupiry',
        
        // Vegetarianas
        'cogumelos': 'Mushrooms',
        'brocolos-tomate-seco': 'Broccoli with Sun-Dried Tomatoes',
        'vegetariana': 'Vegetarian',
        
        // Doces
        'banana-canela': 'Banana with Cinnamon',
        'bananute': 'Bananute',
        'romeu-julieta': 'Romeo and Juliet',
        'nutella': 'Nutella',
        'banoffe': 'Banoffee',
        'rafaello': 'Rafaello',
        
        // Bordas
        'borda-catupiry': 'Stuffed Crust - Catupiry',
        'borda-nutella': 'Stuffed Crust - Nutella',
        
        // Massas
        'spaghetti-bolonhesa': 'Spaghetti Bolognese',
        'spaghetti-carbonara': 'Spaghetti Carbonara',
        'lasanha-carne': 'Beef Lasagna',
        'lasanha-frango': 'Chicken Lasagna',
        'tagliatelle-carbonara': 'Tagliatelle Carbonara',
        'tagliatelle-bolonhesa': 'Tagliatelle Bolognese',
        'fusilli-bolonhesa': 'Fusilli Bolognese',
        'nhoque-bolonhesa': 'Gnocchi Bolognese',
        
        // Todos
        'bitoque': 'Bitoque',
        'parmegiana-frango': 'Chicken Parmigiana',
        'parmegiana-vaca': 'Beef Parmigiana',
        'picanha-grelhada': 'Grilled Picanha',
        'bife-acebolado': 'Steak with Onions',
        'bife-cogumelos': 'Steak with Mushrooms',
        'salsicha-toscana': 'Tuscan Sausage with Onions',
        'bifanas': 'Pork Sandwiches with Onions',
        
        // Sobremesas
        'pudim-leite': 'Condensed Milk Pudding',
        'tiramisu': 'Tiramisu',
        'mousse-limao': 'Lemon Mousse',
        'mousse-maracuja': 'Passion Fruit Mousse',
        'mousse-chocolate': 'Chocolate Mousse',
        
        // Bebidas
        'coca-cola': 'Coca-Cola can 330ml',
        'coca-zero': 'Coca-Cola Zero can 330ml',
        'fanta': 'Fanta can 330ml',
        'guarana': 'Guaraná Antártica can 330ml',
        '7up': '7Up can 330ml',
        'ice-tea-pessego': 'Peach Ice Tea can 330ml',
        'ice-tea-limao': 'Lemon Ice Tea can 330ml',
        'sumos-compal': 'Compal Juices bottle 200ml',
        'agua-tonica': 'Schweppes Tonic Water can 250ml',
        'agua-pedras': 'Água das Pedras bottle 250ml',
        'agua-pedras-limao': 'Água das Pedras Lemon bottle 250ml',
        'agua-castello': 'Castello Water bottle 250ml',
        'agua-500ml': 'Water bottle 500ml',
        'somersby': 'Somersby can 500ml',
        'cerveja-preta': 'Super Bock Stout Beer can 330ml',
        'cerveja-super-bock': 'Super Bock Beer can 330ml',
        'cerveja-sagres': 'Sagres Beer can 330ml',
        'cerveja-brasil': 'Skol or Brahma Beer can 350ml (Brazil)',
        'cerveja-sem-alcool': '0.0% Alcohol-Free Beer bottle 330ml',
        'imperial': 'Imperial (draft) 200ml',
        'caneca': 'Pint 500ml',
        
        // Vinhos
        'vinho-tinto-monte-velho': 'Monte Velho Red Wine bottle 750ml',
        'vinho-branco-monte-velho': 'Monte Velho White Wine bottle 750ml',
        'vinho-tinto-jp': 'JP Red Wine (Bacalhoa) bottle 750ml',
        'vinho-tinto-pinheiros': 'Monte de Pinheiros Red Wine (Cartuxa) bottle 750ml',
        'vinho-tinto-esteva': 'Esteva Red Wine Casa Ferreirinha (Douro) bottle 750ml',
        'vinho-tinto-casa': 'House Red Wine jug 500ml',
        'vinho-branco-casa': 'House White Wine jug 500ml'
      },
      es: {
        // Header and general info
        restaurantName: 'Pizzería Italiana',
        since: 'Desde 1995',
        title: 'Auténtica Pizza Italiana',
        subtitle: 'Hecha con ingredientes importados directamente de Italia',
        yourCart: 'Tu Carrito',
        cart: 'Carrito',
        emptyCart: 'Tu carrito está vacío',
        emptyCartMessage: 'Añade artículos deliciosos para comenzar tu pedido',
        exploreMenu: 'Explorar Menú',
        viewCart: 'Ver Carrito',
        fullMenu: 'Menú Completo',
        ourMenu: 'Nuestro Menú',
        addToCart: 'Añadir al Carrito',
        items: 'artículos',
        subtotal: 'Subtotal',
        deliveryFee: 'Gastos de Envío',
        discount: 'Descuento',
        total: 'Total',
        estimatedTotal: 'Total Estimado',
        free: 'Gratis',
        proceedToCheckout: 'Finalizar Compra',
        newOrder: 'Nuevo Pedido',
        orderNumber: 'Número de Pedido',
        orderConfirmed: '¡Pedido Confirmado!',
        confirmationMessagePickup: '¡Tu pedido está siendo preparado! Recógelo en aproximadamente 30 minutos.',
        confirmationMessageDelivery: '¡Tu pedido está en camino! Entrega en aproximadamente 30-45 minutos.',
        whatsappMessage: '¿Preguntas? Chatea con nosotros en WhatsApp',
        paymentMethodLabel: 'Método de Pago',
        estimatedTime: 'Tiempo Estimado',
        stamps: 'Sellos',
        changeFor: 'Cambio para',
        changeExample: 'ej: 20.00',
        notes: 'Notas',
        notesPlaceholder: '¿Alguna instrucción especial?',
        deliveryInfo: 'Información de Entrega',
        paymentMethod: 'Método de Pago',
        address: 'Dirección',
        addressPlaceholder: 'Calle, número y complemento',
        neighborhood: 'Barrio',
        selectNeighborhood: 'Selecciona tu barrio',
        fullName: 'Nombre Completo',
        phone: 'Teléfono',
        pickup: 'Recoger',
        pickupAddress: 'Av. São Paulo, 123 - Portimão',
        delivery: 'Entrega',
        deliveryArea: 'Entregamos en tu zona',
        viewDeliveryZones: 'Ver zonas de entrega',
        deliveryFee: 'Gastos de Envío',
        backToCart: 'Volver al Carrito',
        cash: 'Efectivo',
        card: 'Tarjeta',
        mbway: 'MBWay',
        mbwayNumber: 'Número MBWay',
        mbwayDescription: 'Pago por MBWay',
        cashDescription: 'Pago en la entrega',
        cardDescription: 'Pago con tarjeta',
        orderSummary: 'Resumen del Pedido',
        stampsDescription: '5€ de descuento por cada 5 sellos',
        size: 'Tamaño',
        border: 'Borde',
        selectBorder: 'Seleccionar Borde',
        noBorder: 'Sin Borde',
        redeemStamps: 'Canjear Sellos',
        stampsRedeemedSuccess: '¡Sellos canjeados con éxito!',
        productAddedToCart: 'Producto añadido al carrito',
        garlicBread: 'Pan de Ajo',
        individualPizza: 'Pizza Individual',
        mediumPizza: 'Pizza Mediana',
        familyPizza: 'Pizza Familiar',
        
        // Menu categories
        entradas: 'Entrantes',
        petiscos: 'Aperitivos',
        tradicionais: 'Tradicionales',
        vegetarianas: 'Vegetarianas',
        doces: 'Postres',
        bordas: 'Bordes',
        massas: 'Pastas',
        todos: 'Todos',
        sobremesas: 'Postres',
        bebidas: 'Bebidas',
        vinhos: 'Vinos',
        invalidRedeemProduct: 'Producto de canje inválido',
        invalidStampsAmount: 'Cantidad de sellos inválida',
        stampsRedeemError: 'Error al canjear sellos',
        
        // Sizes
        individual: 'Individual',
        media: 'Mediana',
        familia: 'Familiar',
        
        // Popular tag
        popular: 'Popular',
        new: 'Nuevo',

        // Menu items translations
        // Entradas
        'azeitonas': 'Aceitunas',
        'pao-alho-simples': 'Pan de Ajo Simple',
        'pao-alho-queijo': 'Pan de Ajo con Queso',
        'pao-alho-queijo-bacon': 'Pan de Ajo con Queso y Bacon',
        
        // Petiscos
        'filezinho-acebolado': 'Filete con Cebolla',
        'batatas-fritas': 'Patatas Fritas',
        'batata-gourmet': 'Patatas Gourmet con Cheddar y Bacon',
        'calabresa-acebolada': 'Calabresa con Cebolla',
        'moelas': 'Mollejas en Salsa con Rebanadas de Pan (Viernes)',
        
        // Tradicionais
        'marguerita': 'Margarita',
        'calabria': 'Calabria',
        'turim': 'Turín',
        'milao': 'Milán',
        'atum': 'Atún',
        'hawai': 'Hawaiana',
        'bolonhesa': 'Boloñesa',
        'alentejana': 'Estilo Alentejo',
        'americana': 'Americana',
        'sorrento': 'Sorrento',
        'pepperoni': 'Pepperoni',
        'frango-catupiry': 'Pollo con Catupiry',
        'calabresa-catupiry': 'Calabresa con Catupiry',
        'brocolos-bacon-catupiry': 'Brócoli con Bacon y Catupiry',
        'capricciosa': 'Caprichosa',
        'brasileira': 'Brasileña',
        'nostra': 'Nostra',
        'quatro-queijos': 'Cuatro Quesos',
        'do-chefe': 'Especial del Chef',
        'carioca': 'Carioca',
        'carbonara': 'Carbonara',
        'camarao-catupiry': 'Camarones con Catupiry',
        'mediterranica': 'Mediterránea',
        'lombo-acebolado': 'Lomo Ahumado con Cebolla',
        'lombo-catupiry': 'Lomo Ahumado con Catupiry',
        
        // Vegetarianas
        'cogumelos': 'Champiñones',
        'brocolos-tomate-seco': 'Brócoli con Tomates Secos',
        'vegetariana': 'Vegetariana',
        
        // Doces
        'banana-canela': 'Plátano con Canela',
        'bananute': 'Bananute',
        'romeu-julieta': 'Romeo y Julieta',
        'nutella': 'Nutella',
        'banoffe': 'Banoffee',
        'rafaello': 'Rafaello',
        
        // Bordas
        'borda-catupiry': 'Borde Relleno - Catupiry',
        'borda-nutella': 'Borde Relleno - Nutella',
        
        // Massas
        'spaghetti-bolonhesa': 'Espagueti a la Boloñesa',
        'spaghetti-carbonara': 'Espagueti a la Carbonara',
        'lasanha-carne': 'Lasaña de Carne',
        'lasanha-frango': 'Lasaña de Pollo',
        'tagliatelle-carbonara': 'Tagliatelle a la Carbonara',
        'tagliatelle-bolonhesa': 'Tagliatelle a la Boloñesa',
        'fusilli-bolonhesa': 'Fusilli a la Boloñesa',
        'nhoque-bolonhesa': 'Ñoquis a la Boloñesa',
        
        // Todos
        'bitoque': 'Bitoque',
        'parmegiana-frango': 'Parmesana de Pollo',
        'parmegiana-vaca': 'Parmesana de Ternera',
        'picanha-grelhada': 'Picanha a la Parrilla',
        'bife-acebolado': 'Bistec con Cebolla',
        'bife-cogumelos': 'Bistec con Champiñones',
        'salsicha-toscana': 'Salchicha Toscana con Cebolla',
        'bifanas': 'Bocadillos de Cerdo con Cebolla',
        
        // Sobremesas
        'pudim-leite': 'Flan de Leche Condensada',
        'tiramisu': 'Tiramisú',
        'mousse-limao': 'Mousse de Limón',
        'mousse-maracuja': 'Mousse de Maracuyá',
        'mousse-chocolate': 'Mousse de Chocolate',
        
        // Bebidas
        'coca-cola': 'Coca-Cola lata 330ml',
        'coca-zero': 'Coca-Cola Zero lata 330ml',
        'fanta': 'Fanta lata 330ml',
        'guarana': 'Guaraná Antártica lata 330ml',
        '7up': '7Up lata 330ml',
        'ice-tea-pessego': 'Té Helado Melocotón lata 330ml',
        'ice-tea-limao': 'Té Helado Limón lata 330ml',
        'sumos-compal': 'Zumos Compal botella 200ml',
        'agua-tonica': 'Agua Tónica Schweppes lata 250ml',
        'agua-pedras': 'Agua das Pedras botella 250ml',
        'agua-pedras-limao': 'Agua das Pedras Limón botella 250ml',
        'agua-castello': 'Agua Castello botella 250ml',
        'agua-500ml': 'Agua botella 500ml',
        'somersby': 'Somersby lata 500ml',
        'cerveja-preta': 'Cerveza Negra Super Bock Stout lata 330ml',
        'cerveja-super-bock': 'Cerveza Super Bock lata 330ml',
        'cerveja-sagres': 'Cerveza Sagres lata 330ml',
        'cerveja-brasil': 'Cerveza Skol o Brahma lata 350ml (Brasil)',
        'cerveja-sem-alcool': 'Cerveza 0.0% sin alcohol botella 330ml',
        'imperial': 'Imperial (caña) 200ml',
        'caneca': 'Caña 500ml',
        
        // Vinhos
        'vinho-tinto-monte-velho': 'Vino Tinto Monte Velho botella 750ml',
        'vinho-branco-monte-velho': 'Vino Blanco Monte Velho botella 750ml',
        'vinho-tinto-jp': 'Vino Tinto JP (Bacalhoa) botella 750ml',
        'vinho-tinto-pinheiros': 'Vino Tinto Monte de Pinheiros (Cartuxa) botella 750ml',
        'vinho-tinto-esteva': 'Vino Tinto Esteva Casa Ferreirinha (Douro) botella 750ml',
        'vinho-tinto-casa': 'Vino Tinto de la casa jarra 500ml',
        'vinho-branco-casa': 'Vino Blanco de la casa jarra 500ml'
      }
    };

    return translations[lang]?.[key] || key;
  };

  

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  return useContext(LanguageContext);
};